spring:
  application:
    name: delivery-management
  profiles:
    include:
      - db
      - common
      - email
      - security
      - google-api
      - kafka
      - ingress

server:
  port: 8282

