spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: nihat@div.edu.az
    password: rxtmqhvr xowm mxam
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
