version: '3.8'  # Using a newer version for better feature support

services:
  # Delivery Application
  delivery-app:
    image: delivery-app.jar  # Ensure this is correct; typically, Docker images aren't specified with .jar extensions
    build:
      context: .  # Assuming Dockerfile is in the same directory as docker-compose.yml
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
    ports:
      - '8080:8080'
    depends_on:
      - db
      - kafka  # Ensuring delivery-app starts after Kafka service is available

  # Postgres Database
  db:
    image: postgres
    ports:
      - "5433:5432"  # Host port 5433 to container port 5432
    environment:
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres:/var/lib/postgresql/data

  # Zookeeper for Kafka
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  # Kafka Service
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

volumes:
  postgres:


